name: Go CI Pipeline

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: |
        cd todoservice
        go mod tidy

    - name: Run tests
      run: |
        cd todoservice
        go test -v ./...
    - name: Build
      run: |
        cd todoservice/cmd/todoapp
        go build -o myapp .
